name: Build FPGA SD image for caliptra-1.x

on:
jobs:
  build_sd_image:
    name: Build 1.x FPGA images
    uses: chipsalliance/caliptra-sw/.github/workflows/fpga-image.yml@caliptra-1.x
    with:
      branch: "caliptra-1.x"
